name: Ribbit Schema Test
on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * 6" # Run EoD friday (so ~1am UTC Saturday) to check if the schema has been patched this week (and email me)
    
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        dotnet-quality: 'preview'
    
    - name: Restore dependencies
      run: dotnet restore Minimaps.Tests
    
    - name: Build
      run: dotnet build Minimaps.Tests --no-restore
    
    - name: Test
      run: dotnet test Minimaps.Tests --no-build --logger:"trx" --results-directory ./TestResults
    
    - name: Debug - List test result files
      if: success() || failure()
      run: |
        echo "Looking for test result files:"
        find . -name "*.trx" -type f
        ls -la TestResults/ || echo "TestResults directory not found"
        ls -la Minimaps.Tests/bin/Debug/net10.0/TestResults/ || echo "Default TestResults directory not found"
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Report
        path: '**/*.trx'
        reporter: dotnet-trx
